# DWAPlannerROS:
acc_lim_x: 5.0  # Berdasarkan percepatan maksimum motor
acc_lim_y: 5.0
acc_lim_theta: 5.0
max_vel_x: 5.0  # Berdasarkan kecepatan maksimum robot
min_vel_x: -5.0
max_vel_y: 5.0
min_vel_y: -5.0
max_vel_trans: 5.0
min_vel_trans: -5.0
max_vel_theta: 5.0
min_vel_theta: -5.0
xy_goal_tolerance: 0.05  # Toleransi posisi berdasarkan kebutuhan
yaw_goal_tolerance: 0.05  # Toleransi orientasi berdasarkan kebutuhan
latch_xy_goal_tolerance: false
sim_time: 2.0
vx_samples: 5
vy_samples: 5
vtheta_samples: 7
path_distance_bias: 2  # Bias jarak lintasan untuk mengurangi deselerasi dan memperbaiki lintasan
goal_distance_bias: 10  # Bias jarak tujuan untuk mengurangi deselerasi dan memperbaiki lintasan
occdist_scale: 2.0  # Skala jarak halangan ditingkatkan untuk menghindari tabrakan
forward_point_distance: 0.3  # Jarak titik depan disesuaikan dengan dimensi robot (600 mm sisi segitiga)
stop_time_buffer: 0.2  # Buffer waktu berhenti
scaling_speed: 1
max_scaling_factor: 0.2
oscillation_reset_dist: 0.05  # Jarak reset osilasi
holonomic_robot: true  # Berdasarkan jenis roda (omniwheel)
