# DWAPlannerROS:
acc_lim_x: 5.0  # Berdasarkan percepatan maksimum motor
acc_lim_y: 5.0
acc_lim_theta: 5.0
max_vel_x: 5.0  # Berdasarkan kecepatan maksimum robot
min_vel_x: -5.0
max_vel_y: 5.0
min_vel_y: -5.0
max_vel_trans: 5.0
min_vel_trans: -5.0
max_vel_theta: 5.0
min_vel_theta: -5.0
xy_goal_tolerance: 0.05  # Toleransi posisi berdasarkan kebutuhan
yaw_goal_tolerance: 0.13  # Toleransi orientasi berdasarkan kebutuhan
latch_xy_goal_tolerance: false
sim_time: 1.0
vx_samples: 20
vy_samples: 5
vtheta_samples: 20
path_distance_bias: 0.5  # Mengurangi deselerasi mendekati halangan
goal_distance_bias: 1.0  # Mempercepat mendekati target tanpa mengurangi kecepatan
occdist_scale: 1.0  # Skala jarak halangan ditingkatkan untuk menghindari tabrakan
forward_point_distance: 0  # Jarak titik depan disesuaikan dengan dimensi robot
stop_time_buffer: 0.1  # Buffer waktu berhenti
scaling_speed: 1
max_scaling_factor: 1
oscillation_reset_dist: 0.05  # Jarak reset osilasi
holonomic_robot: true  # Berdasarkan jenis roda (omniwheel)
