local_costmap:
  global_frame: odom  # Frame global, biasanya /odom untuk odometri
  robot_base_frame: base_link  # Frame dasar robot
  update_frequency: 0.5  # Frekuensi pembaruan costmap dalam Hertz
  publish_frequency: 1.0  # Frekuensi publikasi costmap dalam Hertz
  transform_tolerance: 0.5  # Toleransi waktu untuk transformasi
  static_map: true  #  menggunakan peta statis
  rolling_window: false  # tidak menggunakan jendela bergulir

  width: 1  # Lebar costmap lokal dalam meter
  height: 1  # Tinggi costmap lokal dalam meter
  resolution: 0.05  # Resolusi costmap dalam meter per sel

  # Konfigurasi layer costmap
  plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
      unknown_cost_value: -1
      lethal_cost_threshold: 255
      map_topic: map
      track_unknown_space: false

  inflation_layer:
      inflation_radius: 0.35
      cost_scaling_factor: 1