// Generated by gencpp from file prcs_image/squareInfo.msg
// DO NOT EDIT!


#ifndef PRCS_IMAGE_MESSAGE_SQUAREINFO_H
#define PRCS_IMAGE_MESSAGE_SQUAREINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>

namespace prcs_image
{
template <class ContainerAllocator>
struct squareInfo_
{
  typedef squareInfo_<ContainerAllocator> Type;

  squareInfo_()
    : Header()
    , x1()
    , y1()
    , x2()
    , y2()  {
    }
  squareInfo_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , x1(_alloc)
    , y1(_alloc)
    , x2(_alloc)
    , y2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _x1_type;
  _x1_type x1;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _y1_type;
  _y1_type y1;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _x2_type;
  _x2_type x2;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::prcs_image::squareInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prcs_image::squareInfo_<ContainerAllocator> const> ConstPtr;

}; // struct squareInfo_

typedef ::prcs_image::squareInfo_<std::allocator<void> > squareInfo;

typedef boost::shared_ptr< ::prcs_image::squareInfo > squareInfoPtr;
typedef boost::shared_ptr< ::prcs_image::squareInfo const> squareInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prcs_image::squareInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prcs_image::squareInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prcs_image::squareInfo_<ContainerAllocator1> & lhs, const ::prcs_image::squareInfo_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prcs_image::squareInfo_<ContainerAllocator1> & lhs, const ::prcs_image::squareInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prcs_image

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prcs_image::squareInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prcs_image::squareInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prcs_image::squareInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prcs_image::squareInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prcs_image::squareInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prcs_image::squareInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prcs_image::squareInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0704fd39f5e83cde6f6e22cad4f13346";
  }

  static const char* value(const ::prcs_image::squareInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0704fd39f5e83cdeULL;
  static const uint64_t static_value2 = 0x6f6e22cad4f13346ULL;
};

template<class ContainerAllocator>
struct DataType< ::prcs_image::squareInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prcs_image/squareInfo";
  }

  static const char* value(const ::prcs_image::squareInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prcs_image::squareInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n"
"std_msgs/Int32 x1\n"
"std_msgs/Int32 y1\n"
"std_msgs/Int32 x2\n"
"std_msgs/Int32 y2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::prcs_image::squareInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prcs_image::squareInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct squareInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prcs_image::squareInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prcs_image::squareInfo_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "x1: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRCS_IMAGE_MESSAGE_SQUAREINFO_H
