// Generated by gencpp from file robot_tf_pkg/encoder.msg
// DO NOT EDIT!


#ifndef ROBOT_TF_PKG_MESSAGE_ENCODER_H
#define ROBOT_TF_PKG_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_tf_pkg
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : enc1(0.0)
    , enc2(0.0)
    , enc3(0.0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : enc1(0.0)
    , enc2(0.0)
    , enc3(0.0)  {
  (void)_alloc;
    }



   typedef double _enc1_type;
  _enc1_type enc1;

   typedef double _enc2_type;
  _enc2_type enc2;

   typedef double _enc3_type;
  _enc3_type enc3;





  typedef boost::shared_ptr< ::robot_tf_pkg::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tf_pkg::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::robot_tf_pkg::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::robot_tf_pkg::encoder > encoderPtr;
typedef boost::shared_ptr< ::robot_tf_pkg::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tf_pkg::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tf_pkg::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_tf_pkg::encoder_<ContainerAllocator1> & lhs, const ::robot_tf_pkg::encoder_<ContainerAllocator2> & rhs)
{
  return lhs.enc1 == rhs.enc1 &&
    lhs.enc2 == rhs.enc2 &&
    lhs.enc3 == rhs.enc3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_tf_pkg::encoder_<ContainerAllocator1> & lhs, const ::robot_tf_pkg::encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_tf_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_tf_pkg::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tf_pkg::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tf_pkg::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tf_pkg::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tf_pkg::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tf_pkg::encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tf_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4b6d686f22bba1d178b85e292ca0a20";
  }

  static const char* value(const ::robot_tf_pkg::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4b6d686f22bba1dULL;
  static const uint64_t static_value2 = 0x178b85e292ca0a20ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tf_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tf_pkg/encoder";
  }

  static const char* value(const ::robot_tf_pkg::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tf_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 enc1\n"
"float64 enc2\n"
"float64 enc3\n"
;
  }

  static const char* value(const ::robot_tf_pkg::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tf_pkg::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enc1);
      stream.next(m.enc2);
      stream.next(m.enc3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tf_pkg::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tf_pkg::encoder_<ContainerAllocator>& v)
  {
    s << indent << "enc1: ";
    Printer<double>::stream(s, indent + "  ", v.enc1);
    s << indent << "enc2: ";
    Printer<double>::stream(s, indent + "  ", v.enc2);
    s << indent << "enc3: ";
    Printer<double>::stream(s, indent + "  ", v.enc3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TF_PKG_MESSAGE_ENCODER_H
